databases:
  - name: phygital
    databaseName: phygital
    user: phygital
    plan: free

services:
  - type: web
    name: phygital
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: phygital
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false